### PR TITLE
Update rosa-python-client as a dependency

### PR DESCRIPTION
**Pull request by oharan2**

### CODE REVIEW

**Comment by myakove** [comment]
I don't see any usage of this, why this is needed?

**Comment by oharan2** [comment]
> I don't see any usage of this, why this is needed?

Please see [#159](https://github.com/RedHatQE/ocp-addons-operators-cli/pull/159#issuecomment-1653885810)
The bot is not updating `rosa-python-client` as a dependant chore

**Comment by myakove** [comment]
This pr add Rosa as dependency, not updated right?
Or I missing something?

**Comment by oharan2** [comment]
> This pr add Rosa as dependency, not updated right?

Correct :)

**Comment by myakove** [comment]
> > This pr add Rosa as dependency, not updated right?
> 
> Correct :) But I required "^1.0.28" when the current `poetry.lock` file is pointing at 1.0.24 (hopefully the bot will update).

This repo does not use `rosa-python-client` directly, therefor it shouldn't be depended on it.

Please close this PR

**Pull request closed without merging**
